# Generated by Django 3.2.4 on 2021-06-14 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('maker', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxApp.producttype')),
            ],
        ),
    ]
