# Generated by Django 3.2.4 on 2021-06-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('maker', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxApp.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField()),
                ('hd', models.FloatField()),
                ('ram', models.IntegerField()),
                ('cd', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxApp.product')),
            ],
        ),
    ]
